server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://payment-service:8083
          predicates:
            - Path=/payments/**
        - id: auth-service
          uri: http://auth-service:8085
          predicates:
            - Path=/auth/**
      default-filters:
        - name: JwtAuthFilter

  main:
    web-application-type: reactive