server:
  port: 8081

spring:
  application:
    name: User_service

  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update