server:
  port: 8082

spring:
  application:
    name: Order_service

  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
