server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 465
    username: monsdagi@gmail.com
    password: ypvv zjlp xrar tbit
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
