name: Java Microservices CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    name: CI – Build & Push Docker Images
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Give permission to gradlew
        run: |
          for dir in Auth_service User_service Order_service Payment_service Notification_service Analytics_service Gateway_service; do
            chmod +x "$dir/gradlew"
          done

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker images
        run: |
          username=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          for dir in Auth_service User_service Order_service Payment_service Notification_service Analytics_service Gateway_service; do
            svc=$(echo "$dir" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
            img=ghcr.io/$username/$svc:latest
            echo "Building and pushing $img"
            docker build -t $img ./$dir
            docker push $img
          done

  cd:
    name: CD – Deploy with Docker Compose
    runs-on: ubuntu-latest
    needs: ci
    env:
      REGISTRY: ghcr.io
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull new images & restart stack
        run: |
          docker-compose pull
          docker-compose up -d
